name: Repository events
on:
    push:
        branches:
            - master
            - main
            - feature/*
            - "!develop"
        tags:
            - v1.*
            - "!v1.0.1"
        paths:
            - "**.j"
    pull_request:
        types: [opened, assigned, reopened, synchronize]
    issues:
        types: [opened]

jobs: 
    checout-tests:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4
