name: Manually Triggered
on: 
    workflow_dispatch:
        inputs:
            string:
                description: A String input
                type: string
                required: true
                default: "Default value"
            number:
                description: A number input
                type: number
                required: true
                default: 0 
            option:
                description: An options input
                type: choice
                required: false
                options:
                    - option1
                    - option2
                    - option3
            boolean:
                description: A boolean input
                type: boolean
                required: false
                default: false
            environment:
                description: Environment
                type: environment
                required: true
jobs:
    Manually-Triggering-Jobs:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF
            - run: |
               echo " String:  ${{ inputs.string  }} "
               echo " Number:  ${{ inputs.number  }} "
               echo " Option:  ${{ inputs.option  }} "
               echo " Boolean: ${{ inputs.boolean }} "
               echo " Environment: ${{ inputs.environment }}    "

        

