name: Workflow commands
on: [push]

jobs:
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps: 
            - name: seetting an error command
              run: echo  "::error::This is an error message"
            - name: setting an error with params
              run : "::error::title=Error title"
            
