name: working Dir & Ehell
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                  pwd
                  ls -a
                  echo " 1 ====> $GITHUB_SHA "
                  echo " 2 ====> $GITHUB_REPOSITORY "
                  echo " 3 ====> $GITHUB_WORKSPACE "
    display-wd-info-windows:
        runs-on: windows-latest
        steps:
            - name: Display working directory
              run: | 
                  Get-Location
                  dir
                  echo  $env:$GITHUB_SHA 
                  echo  $env:$GITHUB_REPOSITORY 
                  echo  $env:$GITHUB_WORKSPACE 