name: working Dir & Ehell
on: [push]
defaults:
    run:
        shell: bash
        #working-directory: ./src  we can overide the default working directory ....
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                  pwd
                  ls -a
                  echo " 1 ====> $GITHUB_SHA "
                  echo " 2 ====> $GITHUB_REPOSITORY "
                  echo " 3 ====> $GITHUB_WORKSPACE "
            - name: test changing the default working dir
              working-directory: /home/runner
              run: pwd
              
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display working directory
              run: | 
                  Get-Location
                  dir
                  echo  $env:GITHUB_SHA 
                  echo  $env:GITHUB_REPOSITORY 
                  echo  $env:GITHUB_WORKSPACE 
            - name:  python shell
              shell: python
              run: | 
                import platform 
                print(platform.processor())


                 