name: working Dir & Ehell
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                  pwd
                  ls -a
                  echo "====> $GITHUB_SHA "
                  echo "====>" $GITHUB_REPOSITORY "
                  ecno "====>" $GITYHUB_WORKSPACE "