name: working Dir & Ehell
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                  pwd
                  ls -a
                  echo " 1 ====> $GITHUB_SHA "
                  echo " 2 ====> $GITHUB_REPOSITORY "
                  ecno " 3 ====> $GITHUB_WORKSPACE "