name: working Dir & Ehell
on: [push]
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                  pwd
                  ls -a
                  echo " 1 ====>"  echo  $GITHUB_SHA 
                  echo " 2 ====>" echo  $GITHUB_REPOSITORY 
                  ecno " 3 ====>" echo  $GITHUB_WORKSPACE 